# Secret scanning configuration
# Allowlist for test fixtures in security-scanner package

paths-ignore:
  - 'packages/security-scanner/src/scanners/*.test.ts'
  - 'packages/security-scanner/src/**/*.test.ts'
